<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="149" started-at="2022-09-30T21:35:00 IST" finished-at="2022-09-30T21:35:00 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="149" started-at="2022-09-30T21:35:00 IST" finished-at="2022-09-30T21:35:00 IST">
      <class name="com.testng.properties.Always_Run">
        <test-method status="PASS" signature="laptop()[pri:0, instance:com.testng.properties.Always_Run@15eb5ee5]" name="laptop" duration-ms="40" started-at="2022-09-30T21:35:00 IST" finished-at="2022-09-30T21:35:00 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- laptop -->
        <test-method status="FAIL" signature="mobile()[pri:0, instance:com.testng.properties.Always_Run@15eb5ee5]" name="mobile" duration-ms="0" started-at="2022-09-30T21:35:00 IST" finished-at="2022-09-30T21:35:00 IST">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at com.testng.properties.Always_Run.mobile(Always_Run.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mobile -->
        <test-method status="PASS" signature="offer()[pri:-3, instance:com.testng.properties.Always_Run@15eb5ee5]" name="offer" duration-ms="0" started-at="2022-09-30T21:35:00 IST" depends-on-methods="com.testng.properties.Always_Run.mobile" finished-at="2022-09-30T21:35:00 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- offer -->
      </class> <!-- com.testng.properties.Always_Run -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
